language: c

notifications:
  email: false

before_script:
  - uname -a
  # Create tmp directory to keep things clean
  - mkdir -p tmp
  - cd tmp
  # Install arm-none-eabi-*
  - wget https://sourcery.mentor.com/GNUToolchain/package11442/public/arm-none-eabi/arm-2013.05-23-arm-none-eabi-i686-pc-linux-gnu.tar.bz2
  - tar -xjf https://sourcery.mentor.com/GNUToolchain/package11442/public/arm-none-eabi/arm-2013.05-23-arm-none-eabi-i686-pc-linux-gnu.tar.bz2
  - sudo cp -f -r arm-2013.05/* /usr/
  - arm-none-eabi-as --version
  - arm-none-eabi-gcc --version
  - cd ..

script:
  - make
  - mkdir -p cbuild
  - cd cbuild
  - cmake ..
  - make
  - make test
