language: c

notifications:
  email: false

before_script:
  - uname -a
  # Create tmp directory to keep things clean
  - mkdir -p tmp
  - cd tmp
  # Install arm-none-eabi-*
  - wget https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2012.09-63-arm-none-eabi-i686-pc-linux-gnu.tar.bz2
  - tar xjf arm-2012.09-63-arm-none-eabi-i686-pc-linux-gnu.tar.bz2
  - export PATH=$PATH:$(pwd)/arm-2012.09/bin
  - chmod +x arm-2012.09/bin/arm-none-eabi-as
  - chmod +x arm-2012.09/bin/arm-none-eabi-gcc
  - arm-none-eabi-as --version
  - arm-none-eabi-gcc --version
  - export CROSS_COMPILE=$(pwd)/arm-2012.09/bin/arm-none-eabi-
  - cd ..

script:
  - make
  - mkdir -p cbuild
  - cd cbuild
  - cmake ..
  - make
  - make test
